# Workflow für Deployment einer Flutter Web-App auf GitHub Pages
name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: ["master"]  # läuft bei jedem Push auf master
  workflow_dispatch:      # manuell ausführbar

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # 1. Repository auschecken
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Flutter installieren
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      # 3. Dependencies holen und Web-Build mit korrektem base-href erzeugen
      - name: Build Flutter Web
        run: |
          flutter pub get
          flutter build web --release --base-href /gargano2025/

      # 4. GitHub Pages konfigurieren
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 5. Web-Build hochladen
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/web'

      # 6. Deployment auf GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
